# UAPI Header export list
include include/uapi/asm-generic/Kbuild.asm

header-y += auxvec.h
header-y += bitsperlong.h
header-y += byteorder.h
header-y += ptrace.h
header-y += sigcontext.h
header-y += siginfo.h
header-y += unistd.h
